var CKBUILDER_CONFIG = {
  skin: 'moono',
  preset: 'full',
  ignore: [
    '.bender',
    'bender.js',
    'bender-err.log',
    'bender-out.log',
    'dev',
    '.DS_Store',
    '.editorconfig',
    '.gitattributes',
    '.gitignore',
    'gruntfile.js',
    '.idea',
    '.jscsrc',
    '.jshintignore',
    '.jshintrc',
    'less',
    '.mailmap',
    'node_modules',
    'package.json',
    'README.md',
    'tests',
  ],
  plugins: {
    basicstyles: 1,
    clipboard: 1,
    enterkey: 1,
    entities: 1,
    floatingspace: 1,
    format: 1,
    indentlist: 1,
    justify: 1,
    list: 1,
    magicline: 1,
    toolbar: 1,
    undo: 1,
    wysiwygarea: 1,
  },
  languages: {
    n: 1,
  },
};
